### ISSUE TITLE
Add the possibility to create home ? :)

### ISSUE THREAD

**Issue by EvanSchleret** [TechnoVisionDev/HomeGUI#1]
Hi,

It would be great if we can also create home from the GUI.
This process could be a possibility : 

1. The player run the commande "createhome" without argument.
2. The icon GUI shows up, the player select an icon
3. An anvil gui opens and the player type the name of the home that he want
4. The essentials message createhome is send to the player.

If the player type createhome with the text argument, it do nothing specially.

Thanks ;)

**Comment by Redstoneguy129** [comment]
I've made a fix for that will be in version 1.3

**Comment by TechnoVisionDev** [comment]
This feature has now been added.
